---

- name: Check mongodb exporter
  stat:
    path: /usr/sbin/mongodb_exporter
  register: mongodb_exporter_bin


- name: Download mongodb exporter
  get_url:
    url: https://github.com/percona/mongodb_exporter/releases/download/v0.40.0/mongodb_exporter-0.40.0.linux-amd64.tar.gz 
    dest: /tmp/mongodb_exporter-0.40.0.linux-amd64.tar.gz
  when: mongodb_exporter_bin.stat.exists != true


- name: Extract mongodb exporter
  ansible.builtin.unarchive:
    src: /tmp/mongodb_exporter-0.40.0.linux-amd64.tar.gz
    dest: /usr/sbin
    owner: root
    group: root
    mode: 0755
    remote_src: true
    exclude:
    - LICENSE
    - CHANGELOG
    - README.md
    extra_opts:
    - --strip-components
    - 1
  when: mongodb_exporter_bin.stat.exists != true


- name: Add user for mongodb_exporter
  user:
    name: prometheus
    create_home: no


- name: Copy env file
  template:
    src: mongodb_exporter
    dest: /etc/default/mongodb_exporter
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart mongodb exporter


- name: Copy systemd unit
  copy:
    src: mongodb_exporter.service
    dest: /etc/systemd/system/mongodb_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart mongodb exporter


- name: Start mongodb exporter
  systemd:
    name: mongodb_exporter
    state: started
    daemon_reload: true
    enabled: true
